server:
  port: 8080

dubbo:
  application:
    name: nacos-dubbo-provider-example
  protocol:
    name: dubbo
    port: -1
  registry:
    # 注册地址，对于 nacos、zookeeper 注册地址也是配置中心地址、元数据中心地址 ref: https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/registry/overview/#%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%B8%8E%E5%85%83%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83
    address: nacos://192.168.120.17:8848
    # 隔离统一环境下不用应用 ref: https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/registry/nacos/#33-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%88%86%E7%BB%84
  #    group: example
  #    parameters:
  #      # 指定 namespace 隔离不同的用户或环境（类似泳道） ref: https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/registry/nacos/#32-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4
  #      namespace: ce0f8c5e-8113-402a-8dbe-e087b5c7b3a8
#  provider:
#    filter: metrics
